version: '3'

services:
  apache:
    image: httpd:2.4
    working_dir: /var/www/html
    volumes:
      - ./laravel:/var/www/html
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
      - 443:443
    working_dir: /var/www/html
    volumes:
      - ./laravel:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - apache

  php:
    build:
      ./php
    volumes:
      - ./php/php.ini:/usr/local/etc/php/opcahce.ini
      - ./laravel:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      POSTGRES_PASSWORD: supersecret
      POSTGRES_USER: username
      POSTGRES_DB: dbname
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8765:8080
    depends_on:
      - db

  composer:
    image: composer:1.6
    volumes:
      - ./laravel:/var/www/html
    working_dir: /var/www/html
    command: composer install
  redis:
    image: redis
    restart: always
    volumes:
      - ./storage/redis/data:/data
    ports:
      - 6379:6379
    logging:
      driver: none
